# Created by: bsam
# $FreeBSD: head/multimedia/linux-f10-libv4l/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libv4l
PORTVERSION=	0.6.3
CATEGORIES=	multimedia linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Collection of video4linux support libraries (CentOS 6)

CONFLICTS=	linux-f10-libv4l-[0-9]*

USE_LINUX=	c6
USE_LINUX_RPM=	yes
RPMVERSION=	2.el6
USE_LDCONFIG=	yes
PLIST_SUB+=	PORTVERSION=${PORTVERSION}

.include <bsd.port.mk>
